sudo: required
services:
  - docker

before_install:
  - docker build -t alecin/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true alecin/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-082376044448"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"